### ISSUE TITLE
Issue when assigning to more than one fader

### ISSUE THREAD

**Issue by rds2024-3004** [zsteinkamp/m4l-Knobbler4#10]
Is this a bug? When assigning the same parameter to more than one fader, adjusting one fader doesn’t update the other.

Basically, I want to do this for example I want the parameter in tab1 and in tab2. I tested this before in the previous version without any issue

https://github.com/user-attachments/assets/9601219e-3b98-4de1-b8af-58ded345b35a

**Comment by zsteinkamp** [comment]
Yep I'm getting the same thing here. Thanks for reporting it. I'll have a look in the next day or so. Just wrapping up another project at the moment...

BTW what is the device you're running TouchOSC on?

**Comment by rds2024-3004** [comment]
No worries. I'm using an android phone together with my midi controller.

**Comment by rds2024-3004** [comment]
Hi @zsteinkamp - Just wanted to add what I noticed in Bluehand. Sometimes the parameters wont update when switching between tracks or device, and it will need to manually press the refresh

**Comment by zsteinkamp** [comment]
Hey @rds2024-3004 - give the version v6 a try. Lots of fixes across the board as a result of your report!
The bluhand one will be a little more tricky ... sometimes the network buffers can overflow on one side or the other and the UDP protocol of OSC does not have guarantees of delivery (so no way to know it needs to retry). I've tried tuning the buffers that I can tune in Knobbler4, but I still get this too. Will keep looking...

**Comment by rds2024-3004** [comment]
Thanks it works now. Regarding the bluehand, I think it has to do with my network. I was previously connected my phone to my 2nd router which is an extension. Then after connecting my phone wifi to the main router, it works perfect now

**Comment by zsteinkamp** [comment]
🎉🎉🎉🎉🎉!!!
Thanks for following up :)
